### ISSUE TITLE
请问bios需要做额外的设置吗？

### ISSUE THREAD

**Issue by kiddtam** [tonyleelyy/OpenCore-Hackintosh-Asus-PRIME-B360M-A#1]
您好，今天很巧刚搜索就见到您今天提交的分享，我和您的配置基本一致，不过我是gt710显卡，不知能否和你加个好友探讨一下

**Comment by tonyleelyy** [comment]
BIOS一定要更新至最新版本，然后设置的话，按照这篇文章去做即可：[链接](https://blog.xjn819.com/?p=543)
另外SATA模式要改成AHCI

这个OC是给我的一个朋友做的，我自己没有这台机器，所以具体的设置项名称还是要你自己去耐心研究一下了。
如果安装有报错可以在这里继续提issue。

加好友的话，我不太懂GitHub，不知道能不能私信？感觉我把我的联系方式放在这好像不太好。
