### ISSUE TITLE
OpenCore-Hackintosh for ASUS PRIME Z490M Plus

### ISSUE THREAD

**Issue by vmadhavan15** [tonyleelyy/OpenCore-Hackintosh-Asus-PRIME-B360M-A#2]
Hi Tony.

Could you please make the OpenCore for ASUS PRIME Z490M plus i7 10700k and Intel UHD Graphics BIOS version 1602

Which I have my desktop to install BIG SUR or Catalina.

Thanks in advance

**Comment by tonyleelyy** [comment]
Sorry I don't have that time...
Moreover, making a EFI without that specific computer is too hard for me.
